### ISSUE TITLE
Illegal char escape

### ISSUE THREAD

**Issue by oddtazz** [nadnerb/terraform-bastion#1]
`MacBook-Pro:terraform-bastion:% terraform get`
`Get: file:///Users/SandBox/test/terraform-bastion/bastion
Error loading Terraform: Error downloading modules: module bastion_servers_a: Error parsing .terraform/modules/3c6f38fc0ce138f292adc1bd64b220b0/main.tf: At 20:69: illegal char escape`

`MacBook-Pro:terraform-bastion:% terraform -version
Terraform v0.6.11`

**Comment by oddtazz** [comment]
Here are the steps followed :- 
- `git clone git@github.com:nadnerb/terraform-bastion.git`
- `cd terraform-bastion`
- `terraform get`

This seems to be the offending line :- 
`security_groups = ["${split(",", replace(var.security_groups, "/,\s?$/", ""))}"]`

**Comment by nadnerb** [comment]
Later versions of Terraform require escaping within the regex. Try this, it should work.

**Comment by oddtazz** [comment]
Yup it does.
Thanks
